//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RollCallSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exercise
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime Deadline { get; set; }
        public System.DateTime Start { get; set; }
        public System.DateTime PostDate { get; set; }
        public bool IsRequire { get; set; }
        public int ClassId { get; set; }
    
        public virtual Class Class { get; set; }
    }
}
