//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RollCallSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaceTrainedStudent
    {
        public int id { get; set; }
        public string link_image { get; set; }
        public int mssv { get; set; }
    
        public virtual StudentInformation StudentInformation { get; set; }
    }
}
