//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RollCallSystem.Models
{
    using System;
    using System.Collections.Generic;
    
     using System.Runtime.Serialization;
     using Newtonsoft.Json;
    
     [DataContract(IsReference =true)]
     [JsonObject(MemberSerialization.OptOut)]
    public partial class Khoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Khoa()
        {
            this.StudentInformations = new List<StudentInformation>();
            this.TeacherInformations = new List<TeacherInformation>();
        }
    
    	[DataMember]
        public int ma_khoa { get; set; }
    	[DataMember]
        public string ten_khoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	[DataMember]
        public virtual List<StudentInformation> StudentInformations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	[DataMember]
        public virtual List<TeacherInformation> TeacherInformations { get; set; }
    }
}
