//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RollCallSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesDB : DbContext
    {
        public EntitiesDB()
            : base("name=EntitiesDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<ClassSchedule> ClassSchedules { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Exercise> Exercises { get; set; }
        public virtual DbSet<Faculty> Faculties { get; set; }
        public virtual DbSet<FileAttachment> FileAttachments { get; set; }
        public virtual DbSet<FileData> FileDatas { get; set; }
        public virtual DbSet<Major> Majors { get; set; }
        public virtual DbSet<MajorSpecialty> MajorSpecialties { get; set; }
        public virtual DbSet<RollCall> RollCalls { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Studying> Studyings { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<TrainingImage> TrainingImages { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
