//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RollCallSystem.Models
{
    using System;
    using System.Collections.Generic;
    
     using System.Runtime.Serialization;
     using Newtonsoft.Json;
    
     [DataContract(IsReference =true)]
     [JsonObject(MemberSerialization.OptOut)]
    public partial class RollCall
    {
    	[DataMember]
        public int StudentId { get; set; }
    	[DataMember]
        public int ClassScheduleId { get; set; }
    	[DataMember]
        public System.DateTime CreatedDate { get; set; }
    	[DataMember]
        public int Type { get; set; }
    	[DataMember]
        public Nullable<int> ImageId { get; set; }
    	[DataMember]
        public bool IsActive { get; set; }
    
    	[DataMember]
        public virtual ClassSchedule ClassSchedule { get; set; }
    	[DataMember]
        public virtual FileAttachment FileAttachment { get; set; }
    	[DataMember]
        public virtual Student Student { get; set; }
    }
}
