//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RollCallSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleTeach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScheduleTeach()
        {
            this.RollCallStudents = new HashSet<RollCallStudent>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> date_teach { get; set; }
        public Nullable<int> ma_mon { get; set; }
        public Nullable<int> teacher_id { get; set; }
        public string phong_hoc { get; set; }
        public Nullable<System.TimeSpan> time_teach { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<int> buoi { get; set; }
    
        public virtual MonHoc MonHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RollCallStudent> RollCallStudents { get; set; }
        public virtual Status Status { get; set; }
        public virtual TeacherInformation TeacherInformation { get; set; }
    }
}
