//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RollCallSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentInformation()
        {
            this.FaceTrainedStudents = new HashSet<FaceTrainedStudent>();
            this.RollCallStudents = new HashSet<RollCallStudent>();
            this.StudentMHs = new HashSet<StudentMH>();
        }
    
        public int mssv { get; set; }
        public string name_student { get; set; }
        public string user_name { get; set; }
        public string password { get; set; }
        public string token { get; set; }
        public Nullable<int> age { get; set; }
        public string email { get; set; }
        public Nullable<decimal> number_phone { get; set; }
        public string address { get; set; }
        public int ma_khoa { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string home_town { get; set; }
        public Nullable<int> course { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FaceTrainedStudent> FaceTrainedStudents { get; set; }
        public virtual Khoa Khoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RollCallStudent> RollCallStudents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentMH> StudentMHs { get; set; }
    }
}
