//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RollCallSystem.Models
{
    using System;
    using System.Collections.Generic;
    
     using System.Runtime.Serialization;
     using Newtonsoft.Json;
    
     [DataContract(IsReference =true)]
     [JsonObject(MemberSerialization.OptOut)]
    public partial class StudentInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentInformation()
        {
            this.FaceTrainedStudents = new List<FaceTrainedStudent>();
            this.RollCallStudents = new List<RollCallStudent>();
            this.StudentMHs = new List<StudentMH>();
        }
    
    	[DataMember]
        public int mssv { get; set; }
    	[DataMember]
        public string name_student { get; set; }
    	[DataMember]
        public string user_name { get; set; }
    	[DataMember]
        public string password { get; set; }
    	[DataMember]
        public string token { get; set; }
    	[DataMember]
        public Nullable<int> age { get; set; }
    	[DataMember]
        public string email { get; set; }
    	[DataMember]
        public Nullable<decimal> number_phone { get; set; }
    	[DataMember]
        public string address { get; set; }
    	[DataMember]
        public int ma_khoa { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> birthday { get; set; }
    	[DataMember]
        public string home_town { get; set; }
    	[DataMember]
        public Nullable<int> course { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	[DataMember]
        public virtual List<FaceTrainedStudent> FaceTrainedStudents { get; set; }
    	[DataMember]
        public virtual Khoa Khoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	[DataMember]
        public virtual List<RollCallStudent> RollCallStudents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	[DataMember]
        public virtual List<StudentMH> StudentMHs { get; set; }
    }
}
