//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RollCallSystem.Models
{
    using System;
    using System.Collections.Generic;
    
     using System.Runtime.Serialization;
     using Newtonsoft.Json;
    
     [DataContract(IsReference =true)]
     [JsonObject(MemberSerialization.OptOut)]
    public partial class StudentMH
    {
    	[DataMember]
        public int id { get; set; }
    	[DataMember]
        public int mssv { get; set; }
    	[DataMember]
        public int ma_mon { get; set; }
    	[DataMember]
        public Nullable<bool> is_suspended { get; set; }
    
    	[DataMember]
        public virtual MonHoc MonHoc { get; set; }
    	[DataMember]
        public virtual StudentInformation StudentInformation { get; set; }
    }
}
