//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RollCallSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingImage
    {
        public int Id { get; set; }
        public int StudentId { get; set; }
        public int FileId { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual FileAttachment FileAttachment { get; set; }
        public virtual Student Student { get; set; }
    }
}
